### PR TITLE
updates

### PR DESCRIPTION
**Pull request by mambax7**

### CODE REVIEW

**Comment by liomj** [comment]
1. after creating category, quiz ..user is redirect to home 
2. in question tab cant create question 
3. in question tab modules/xquiz/admin/images/delete.png is missing

**Review by liomj — COMMENTED** [review]
duplicate

**Comment by liomj** [comment]
Hi Mamba any new update on this  module ?

**Comment by mambax7** [comment]
Sorry, I'm behind :(

**Comment by mambax7** [comment]
1) when creating category, quiz ..user is redirect to home 
     it will have to stay that way for the time being (too much work to change it)
2) in question tab cant create question 
     seems to be working now
3) in question tab modules/xquiz/admin/images/delete.png is missing 
    fixed now
    
Please download the code from https://github.com/mambax7/xquiz and see if it works for you, and let me know....

**Pull request merged**
